### ISSUE TITLE
Panic if smart card not present

### ISSUE THREAD

**Issue by maufl** [github/smimesign#33]
Hey, I use a certificate on a smart card. If I don't have the smart card inserted, the tol panics.

```
$ git revert -S HEAD
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x555585]

goroutine 1 [running]:
github.com/github/smimesign/vendor/github.com/mastahyeti/certstore.(*winPrivateKey).Public(0x0, 0xc0000716b0, 0x4)
        c:/gopath/src/github.com/github/smimesign/vendor/github.com/mastahyeti/certstore/certstore_windows.go:356 +0x5
github.com/github/smimesign/vendor/github.com/mastahyeti/cms/protocol.(*SignedData).AddSignerInfo(0xc00005af70, 0xc000081e68, 0x1, 0x1, 0x799c80, 0x0, 0x0, 0x0)
        c:/gopath/src/github.com/github/smimesign/vendor/github.com/mastahyeti/cms/protocol/protocol.go:587 +0x53
github.com/github/smimesign/vendor/github.com/mastahyeti/cms.(*SignedData).Sign(0xc0000060b0, 0xc000081e68, 0x1, 0x1, 0x799c80, 0x0, 0x0, 0xc000014c30)
        c:/gopath/src/github.com/github/smimesign/vendor/github.com/mastahyeti/cms/sign.go:48 +0x67
main.commandSign(0xc000000008, 0x79b3a8)
        c:/gopath/src/github.com/github/smimesign/command_sign.go:49 +0x254
main.runCommand(0x0, 0x0)
        c:/gopath/src/github.com/github/smimesign/main.go:97 +0x27c
main.main()
        c:/gopath/src/github.com/github/smimesign/main.go:52 +0x2d
error: gpg failed to sign the data
fatal: failed to write commit object
```

**Comment by maufl** [comment]
I downloaded it just yesterday.
```
$ smimesign.exe --version
0.0.6
```
I'm on Windows, using the 64 bit version.
